# Addition and Scalar Multiplication

In [1]:
import numpy as np

A = np.array([
    [1, 2, 4],
    [5, 3, 2]
])

B = np.array([
    [1, 3, 4],
    [1, 1, 1]
])

s = 2

display(A)
display(B)
s

array([[1, 2, 4],
       [5, 3, 2]])

array([[1, 3, 4],
       [1, 1, 1]])

2

In [2]:
A + B

array([[2, 5, 8],
       [6, 4, 3]])

In [3]:
A - B

array([[ 0, -1,  0],
       [ 4,  2,  1]])

In [4]:
A * s

array([[ 2,  4,  8],
       [10,  6,  4]])

In [5]:
A / s

array([[ 0.5,  1. ,  2. ],
       [ 2.5,  1.5,  1. ]])

In [6]:
A + s

array([[3, 4, 6],
       [7, 5, 4]])

# Matrix-Vector Multiplication

In [7]:
A = np.arange(1, 10).reshape(3, 3)
v = np.ones(3).reshape(3, 1)
display(A)
display(v)

A.dot(v)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[ 1.],
       [ 1.],
       [ 1.]])

array([[  6.],
       [ 15.],
       [ 24.]])

# Matrix-Matrix Multiplication

In [8]:
A = np.arange(1, 7).reshape(3, 2)
B = np.arange(1, 3).reshape(2, 1)

display(A)
display(B)
A.dot(B)

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1],
       [2]])

array([[ 5],
       [11],
       [17]])

# Matrix Multiplication Properties

In [9]:
A = np.array([
    [1, 2],
    [4, 5]
])

B = np.array([
    [1, 1],
    [0, 2]
])

I = np.identity(2)

display(A)
display(B)
I

array([[1, 2],
       [4, 5]])

array([[1, 1],
       [0, 2]])

array([[ 1.,  0.],
       [ 0.,  1.]])

In [10]:
I.dot(A)

array([[ 1.,  2.],
       [ 4.,  5.]])

In [11]:
A.dot(I)

array([[ 1.,  2.],
       [ 4.,  5.]])

In [12]:
A.dot(B)

array([[ 1,  5],
       [ 4, 14]])

In [13]:
B.dot(A)

array([[ 5,  7],
       [ 8, 10]])

# Inverse and Transpose

In [14]:
A = np.array([
    [1, 2, 0],
    [0, 5, 6],
    [7, 0, 9]
])

A

array([[1, 2, 0],
       [0, 5, 6],
       [7, 0, 9]])

In [15]:
A.transpose()

array([[1, 0, 7],
       [2, 5, 0],
       [0, 6, 9]])

In [16]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.34883721, -0.13953488,  0.09302326],
       [ 0.3255814 ,  0.06976744, -0.04651163],
       [-0.27131783,  0.10852713,  0.03875969]])

In [17]:
A_inv.dot(A)

array([[  1.00000000e+00,   0.00000000e+00,   1.80411242e-16],
       [  2.08166817e-17,   1.00000000e+00,   3.46944695e-17],
       [ -3.46944695e-17,   0.00000000e+00,   1.00000000e+00]])